---
title: "Events"
---
### Workshops taking place in 2025

- Career Mapping for Female Researchers (June 2025)

- Unconscious Bias (planned for Autumn 2025)

- Managing Microaggresions in the Workplace (planned for Autumn 2025)
Career Mapping for Female Researchers (June 2025)

- Unconscious Bias (planned for Autumn 2025)

- Managing Microaggresions in the Workplace (planned for Autumn 2025)

 
### Previous workshops 

- Supporting the Mental Well-Being of Our People: A Useful Toolbox For PIs (November 2024)
Facilitated by Dickerson et al.

- Resilience and Well-Being in Academia (July 2024)
Facilitated by Dickerson et al.

- Oblivious Sexism in Academia 101 (April 2024)
Facilitated by the SFB's Mercator Fellow

- Salary negotiation for female researchers (April 2023)
Facilitated by Tina Groll

- Leadership skills for female researchers   
Facilitated by Svenja Neupert (November 2022)

### Outreach

- The Women in Research Initiative in the SFB 1287: What we do and where we are heading (December 2023)

Presentation made to the CSLM LAB (SFB 1287 Project B05)
